name: MinecraftSocial
main: de.mcsocial.main.MCSocial
version: 0.0.0.1.1
author: MuellerMH
commands:
  menu:
    aliases: [m]
    description: Zeigt das Spielermenu
    usage: 
    permission: MCSocial.menu
    permission-message: You do not have Permission MCSocial.menu
  miner:
    description: Display Player Mining
    usage: /miner UserName
    permission: MCSocial.miner
    permission-message: You do not have Permission MCSocial.miner
  infoitem:
    description: Display Player in Hand Item Info
    usage: /infoitem  (Hold Item in Hand)
    permission: MCSocial.miner
    permission-message: You do not have Permission MCSocial.infoitem
  gs:
    description: Display Player Mining
    usage: /gs
    permission: MCSocial.gs
    permission-message: You do not have Permission MCSocial.gs
  join:
    description: Betritt einen Chatraum
    usage: /join ChannelName
    permission: MCSocial.join
    permission-message: You do not have Permission MCSocial.join
  leave:
    description: Verlaesst einen Chatraum
    usage: /leave ChannelName
    permission: MCSocial.leave
    permission-message: You do not have Permission MCSocial.leave
  list:
    description: zeigt alle chatrauume
    usage: /list
    permission: MCSocial.list
    permission-message: You do not have Permission MCSocial.list
  shop:
    description: Erstellt einen NPC Shop
    usage: /shop [add/remove] [Name] {Profession}
    permission: MCSocial.shop
    permission-message: You do not have Permission MCSocial.shop
  g:
    description: Betreten des Chat Global
    usage: /g
    permission: MCSocial.g
    permission-message: You do not have Permission MCSocial.g
  l:
    description: Betreten des Chat Lokal
    usage: /l
    permission: MCSocial.l
    permission-message: You do not have Permission MCSocial.l
  h:
    description: Betreten des Handel Global
    usage: /h
    permission: MCSocial.h
    permission-message: You do not have Permission MCSocial.h
  a:
    description: Betreten des Chat Admin
    usage: /a
    permission: MCSocial.a
    permission-message: You do not have Permission MCSocial.a
  s:
    description: Betreten des Chat Support
    usage: /s
    permission: MCSocial.s
    permission-message: You do not have Permission MCSocial.s
  kick:
    description: Betreten des Chat Support
    usage: /kick [player] [message]
    permission: MCSocial.kick
    permission-message: You do not have Permission MCSocial..kick
  ban:
    description: Betreten des Chat Support
    usage: /ban [player]
    permission: MCSocial.ban
    permission-message: You do not have Permission MCSocial..ban
  timeban:
    description: Betreten des Chat Support
    usage: /timeban [player] [minutes]
    permission: MCSocial.timeban
    permission-message: You do not have Permission MCSocial.timeban
  give:
    description: gibt Gegenstand in der Hand dem Spieler
    usage: /give [player]
    permission: MCSocial.give
    permission-message: You do not have Permission MCSocial.give
  money:
    description: Betreten des Chat Support
    usage: /money [player] [amount]
    permission: MCSocial.money
    permission-message: You do not have Permission MCSocial.money
  tp:
    description: Betreten des Chat Support
    usage: /tp [player] [player]
    permission: MCSocial.tp
    permission-message: You do not have Permission MCSocial.tp
  gm:
    description: Betreten des Chat Support
    usage: /gm
    permission: MCSocial.gm
    permission-message: You do not have Permission MCSocial.gm
  fly:
    description: Betreten des Chat Support
    usage: /fly
    permission: MCSocial.fly
    permission-message: You do not have Permission MCSocial.fly
  debug:
    description: Betreten des Chat Support
    usage: /debug
    permission: MCSocial.fly
    permission-message: You do not have Permission MCSocial.debug
permissions:
  MCSocial.*:
    children:
      MCSocial.menu: true
      MCSocial.miner: false
      MCSocial.infoitem: true
      MCSocial.gs: true
      MCSocial.join: true
      MCSocial.leave: true
      MCSocial.list: true
      MCSocial.shop: true
      MCSocial.g: true
      MCSocial.l: true
      MCSocial.h: true
      MCSocial.a: true
      MCSocial.s: true
      MCSocial.kick: false
      MCSocial.ban: false
      MCSocial.timeban: false
      MCSocial.give: false
      MCSocial.money: false
      MCSocial.tp: false
      MCSocial.fly: false
      MCSocial.debug: false
  MCSocial.menu:
    default: true
  MCSocial.miner:
    default: false
  MCSocial.miner:
    default: true
  MCSocial.gs:
    default: true
  MCSocial.join:
    default: true
  MCSocial.leave:
    default: true
  MCSocial.list:
    default: true
  MCSocial.shop:
    default: op
  MCSocial.g:
    default: true
  MCSocial.l:
    default: true
  MCSocial.h:
    default: true
  MCSocial.a:
    default: true
  MCSocial.s:
    default: true
  MCSocial.kick:
    default: false
  MCSocial.ban:
    default: false
  MCSocial.timeban:
    default: false
  MCSocial.money:
    default: false
  MCSocial.give:
    default: false
  MCSocial.fly:
    default: false
  MCSocial.gm:
    default: false
  MCSocial.debug:
    default: false