name: MinecraftSocial
main: de.mcsocial.main.MCSocial
version: 0.0.0.1.1
author: MuellerMH
commands:
  menu:
    aliases: [m]
    description: Zeigt das Spielermenu
    usage: 
    permission: MCSocial.menu
    permission-message: You do not have Permission MCSocial.menu
  miner:
    description: Display Player Mining
    usage: /miner UserName
    permission: MCSocial.miner
    permission-message: You do not have Permission MCSocial.miner
  gs:
    description: Display Player Mining
    usage: /gs
    permission: MCSocial.gs
    permission-message: You do not have Permission MCSocial.gs
  join:
    description: Betritt einen Chatraum
    usage: /join ChannelName
    permission: MCSocial.join
    permission-message: You do not have Permission MCSocial.join
  leave:
    description: Verlaesst einen Chatraum
    usage: /leave ChannelName
    permission: MCSocial.leave
    permission-message: You do not have Permission MCSocial.leave
  list:
    description: zeigt alle chatrauume
    usage: /list
    permission: MCSocial.list
    permission-message: You do not have Permission MCSocial.leave
  shop:
    description: Erstellt einen NPC Shop
    usage: /shop [add/remove] [Name] {Profession}
    permission: MCSocial.shop
    permission-message: You do not have Permission MCSocial.shop
  g:
    description: Betreten des Chat Global
    usage: /g
    permission: MCSocial.g
    permission-message: You do not have Permission MCSocial.shop
  l:
    description: Betreten des Chat Lokal
    usage: /l
    permission: MCSocial.l
    permission-message: You do not have Permission MCSocial.shop
  h:
    description: Betreten des Handel Global
    usage: /h
    permission: MCSocial.h
    permission-message: You do not have Permission MCSocial.shop
  a:
    description: Betreten des Chat Admin
    usage: /a
    permission: MCSocial.a
    permission-message: You do not have Permission MCSocial.shop
  s:
    description: Betreten des Chat Support
    usage: /s
    permission: MCSocial.s
    permission-message: You do not have Permission MCSocial.shop
permissions:
  MCSocial.*:
    children:
      MCSocial.menu: true
      MCSocial.miner: false
      MCSocial.gs: true
      MCSocial.join: true
      MCSocial.leave: true
      MCSocial.list: true
      MCSocial.shop: true
      MCSocial.g: true
      MCSocial.l: true
      MCSocial.h: true
      MCSocial.a: true
      MCSocial.s: true
  MCSocial.menu:
    default: true
  MCSocial.miner:
    default: false
  MCSocial.gs:
    default: true
  MCSocial.join:
    default: true
  MCSocial.leave:
    default: true
  MCSocial.list:
    default: true
  MCSocial.shop:
    default: op
  MCSocial.g:
    default: true
  MCSocial.l:
    default: true
  MCSocial.h:
    default: true
  MCSocial.a:
    default: true
  MCSocial.s:
    default: true