name: Build sample Java Maven project

on: [push, pull_request]

jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11, 12, 13]
    name: Java ${{ matrix.java }} compile
    steps:
      - uses: actions/checkout@master
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - run: mvn clean compile
  build:
    runs-on: ubuntu-latest
    needs: compile
    name: Build Maven project
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build and test project
        run: mvn clean verify
      - name: Upload Maven build artifact
        uses: actions/upload-artifact@v1
        with:
          name: artifact
          path: release/mcsocial.jar
  release:
    runs-on: ubuntu-latest
    needs: build
    name: Release Maven project
    steps:
      - name: Release
        uses: qcastel/github-actions-maven-release@master
        with:
          release-branch-name: "master"

          git-release-bot-name: "release-bot"
          git-release-bot-email: "release-bot@example.com"

          access-token: ${{ secrets.SECRETTOKEN }}
